### ISSUE TITLE
Kamon - Akka - Java - InstrumentedEnvelope not serializable

### ISSUE THREAD

**Issue by pawelciesielka** [kamon-io/kamon-akka#13]
Hi,
we have a problem while creating persistent mailbox.

While akka.kamon.instrumentation.InstrumentedEnvelope is not serializable  and we can't persist EnvelopeContext so we persist just envelope - but after unpersisting envelope  we have NullPointerException in        (AkkaMonitor.scala(58) -> Tracer.withContext(envelopeContext.context) 
 because  EnvelopeContext is null.

Is there a way to persist envelope with envelopeContext, or apply new context while unpersisting envelope with message?

Here is the exception:
```
java.lang.NullPointerException: null
 at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:58)
 at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:44)
 at akka.actor.ActorCell.invoke(ActorCell.scala:488)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
 at akka.dispatch.Mailbox.run(Mailbox.scala:224)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
 at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by pawelciesielka** [comment]
Code to test the issue is in the attachment :
To run test app:

1. start mongoDB database on  default instalation "localhost:27017" schema "test"
or you can change defaults by adding

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/mySchema

to src\main\resources\application.yml

2. use gradle bootRun task to run examle.

In build.gradle file in line 67  I've set aspectjweaver to run application with kamon. In order to run test app with no kamon just comment out this line.

You should notice that activation of kamon makes akka.dispatch.Envelope become unserializable.​
[persistable_mailbox.zip](https://github.com/kamon-io/kamon-akka/files/980183/persistable_mailbox.zip)

**Comment by pjfanning** [comment]
@pawelciesielka could you try modifying kamon-akka by getting latest source and updating EnvelopeInstrumentation.scala to have

```
trait InstrumentedEnvelope extends Serializable {
  def envelopeContext(): EnvelopeContext
  def setEnvelopeContext(envelopeContext: EnvelopeContext): Unit
}
```

Try building this into a new kamon-akka jar and see if that fixes your test case.

**Comment by pjfanning** [comment]
I tried adding a unit test but it works with the existing code - https://github.com/pjfanning/kamon-akka/commit/8fc1981f91e03eb3066d139699196216c62ae3ae

**Comment by pjfanning** [comment]
I extended the test case and did get a serialization and then fixed itI extended the test case and did get a serialization and then fixed it

**Comment by ivantopo** [comment]
thanks @pjfanning! The PR looks fine, I just published a snapshot in our repo [1].. @pawelciesielka could you please give it a try?

[1]: https://bintray.com/kamon-io/snapshots/kamon-akka/0.6.7-4ebfcb4a0588c886bd418917451ed0703027a409

**Comment by pjfanning** [comment]
@ivantopo I ended up making a 2nd commit as part of the PR after reproducing a serialization error. Then I modified the main source to fix this error. Would it be feasible to merge this PR?

**Comment by ivantopo** [comment]
@pjfanning sure! tests are passing :grinning:, I just would like to get confirmation that it indeed solves the issue before merging, maybe there is something else that needs to be taken care of...

**Comment by pawelciesielka** [comment]
Thanks for fast response, I'will test it and let you know if there is no other problems ...

**Comment by pjfanning** [comment]
@pawelciesielka have you had a chance to check the fix?

**Comment by pawelciesielka** [comment]
Hi, I had tested your fix and in context of serialization it works fine, but now I have another probem.
Hi, I ` tested tour fix and in context of serialization it works now but I have another problem.
1. I can't store Envelope in  MongoDB -> I can store elements ( message, sender, system) and then based on stored parts I can create Envelope back.
2. But after seting Kamon in  1.  I have an error:

```
	java.lang.NullPointerException: null
	at akka.kamon.instrumentation.ActorMonitors$TrackedActor.processMessage(ActorMonitor.scala:84)
	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
	at akka.actor.ActorCell.invoke(ActorCell.scala:481)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```	

It is because there is no Kamon context recreated envelope
	
3. While serializing works fine , de-serializing  throws exception:
```
java.lang.NullPointerException
 at akka.actor.DeadLetterActorRef$SerializedDeadLetterActorRef.readResolve(ActorRef.scala:507)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1817)
```
Is there any Kamon config to fix it or I have to write my own aspect which will add Kamon context while de-serializing from database ?

**Comment by pjfanning** [comment]
@pawelciesielka I suspect you will need to add more aspectJ instrumentation as you suggest above. Could you track this in a separate issue?

**Comment by pawelciesielka** [comment]
Yes, thanks for your help.

**Comment by jcroig** [comment]
Hi,

I'm experiencing this issue as well @pawelciesielka could you please tell me whether you finally find how to fix it?
